bag/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

community/urls.py
from django.urls import path
from . import views


app_name = 'community'


urlpatterns = [
    path('', views.community_view, name='community'),
    path('add-post/', views.add_post, name='add_post'),
    path('testimonials/', views.testimonials_view, name='testimonials'),
    path('add-testimonial/', views.add_testimonial, name='add_testimonial'),
]

peakpulse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('exercises/', include('exercises.urls')),
    path('community/', include('community.urls')),
    path('subscriptions/', include('subscriptions.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Post by {self.user.username} at {self.created_at}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.post}'


class Testimonial(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Testimonial by {self.user.username} at {self.created_at}'

community/forms.py
from django import forms
from .models import Post, Testimonial


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']


class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['content']

community/views.py
from django.shortcuts import render, redirect
from .models import Post, Testimonial
from .forms import PostForm, TestimonialForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from decorators import subscription_required


@subscription_required
def community_view(request):
    """ A view to show all posts, including sorting """
    posts = Post.objects.all()
    return render(request, 'community/community.html', {'posts': posts})


@login_required
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            # Save the post
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            # Add a success message
            messages.success(request, 'Post added successfully!')
            # Redirect to the community page
            return redirect('community:community')
        else:
            # Add an error message if the form is not valid
            messages.error(request, 'Failed to add post. Please check the form.')
    else:
        form = PostForm()
    return render(request, 'community/add_post.html', {'form': form})


def testimonials_view(request):
    """ A view to display testimonials """
    testimonials = Testimonial.objects.all().order_by('-created_at')
    return render(request, 'community/testimonials.html', {'testimonials': testimonials})


@login_required
def add_testimonial(request):
    if request.method == 'POST':
        form = TestimonialForm(request.POST)
        if form.is_valid():
            # Save the testimonial
            testimonial = form.save(commit=False)
            testimonial.user = request.user
            testimonial.save()
            # Add a success message
            messages.success(request, 'Testimonial added successfully!')
            # Redirect to the testimonials page
            return redirect('community:testimonials')
        else:
            # Add an error message if the form is not valid
            messages.error(request, 'Failed to add testimonial. Please check the form.')
    else:
        form = TestimonialForm()
    return render(request, 'community/add_testimonial.html', {'form': form})

community/templates/community/add_post.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Add New Post</h2>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="content">Content:</label>
                    <textarea class="form-control" id="content" name="content" rows="5"></textarea>
                </div>
                <button type="submit" class="btn btn-black rounded-0">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

community/templates/community/add_testimonial.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Add Testimonial</h2>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST" class="mt-3">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.content }}
                </div>
                <button type="submit" class="btn btn-outline-black rounded-0 mt-3">Submit Testimonial</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
		$('.btt-link').click(function(e) {
			window.scrollTo(0,0)
		})
	</script>
{% endblock %}

community/templates/community/community.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Community Wall</h2>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div id="community-posts" class="row justify-content-center mt-5">
        {% for post in posts %}
        <div class="col-md-8 mb-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0" style="font-size: 16px;">Posted by: {{ post.user.username }}</h5>
                    <p class="card-text mb-1" style="font-size: 14px;">Created at: {{ post.created_at }}</p>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ post.content }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-md-8 text-center">
            <p>No posts available</p>
        </div>
        {% endfor %}
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <a href="{% url 'community:add_post' %}" class="btn btn-outline-black rounded-0 mt-3">Post your achievements!</a>
        </div>
    </div>    
</div>
<div class="btt-button shadow-sm rounded-0 border border-black">
    <a class="btt-link d-flex h-100">
        <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
    </a>	
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
		$('.btt-link').click(function(e) {
			window.scrollTo(0,0)
		})
	</script>
{% endblock %}

community/templates/community/testimonials.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Testimonials</h2>
        </div>
    </div>
    <div class="row">
        <div class="testimonial-container col-10 offset-1">
            {% for testimonial in testimonials %}
            <div class="row mt-3">
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{{ testimonial.content }}</p>
                            <p class="card-text"><small class="text-muted">Posted by: {{ testimonial.user.username }}</small></p>
                            <p class="card-text"><small class="text-muted">Created at: {{ testimonial.created_at }}</small></p>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col text-center mt-3">
                <p>No testimonials available</p>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <a href="{% url 'community:add_testimonial' %}" class="btn btn-outline-black rounded-0 mt-3">Add Testimonial</a>
        </div>
    </div>
</div>
<div class="btt-button shadow-sm rounded-0 border border-black">
    <a class="btt-link d-flex h-100">
        <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
    </a>	
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
		$('.btt-link').click(function(e) {
			window.scrollTo(0,0)
		})
	</script>
{% endblock %}